inherit_from: "configs/mono/tum/base_config.yaml"

Dataset:
  dataset_path: "datasets/TUM/rgbd_dataset_freiburg1_360"
  Calibration:
    fx: 517.3
    fy: 516.5
    cx: 318.6
    cy: 255.3
    k1: 0.2624
    k2: -0.9531
    p1: -0.0054
    p2: 0.0026
    k3: 1.1633
    width: 640
    height: 480
    depth_scale: 200.0
    distorted: True

opt_params:
    position_lr_init: 0.0016
    position_lr_final: 0.00016
    init_lr: 6

Training:
    alpha: 0.98
    mapping_itr_nosingle: 10
