inherit_from: "configs/mono/KITTI/base_config.yaml"

Dataset:
  dataset_path: "datasets/KITTI/seq5"
  begin: 0
  end: 235
  Calibration:
    fx: 472.649551
    fy: 472.649551
    cx: 320.000000
    cy: 256.000000
    k1: 0
    k2: 0
    p1: 0
    p2: 0.0
    k3: 0.0
    width: 640
    height: 512
    depth_scale: 100.0
    distorted: False

opt_params:
    position_lr_init: 0.0016
    position_lr_final: 0.00016
    init_lr: 6

Training:
    #alpha: 0.98
    mapping_itr_nosingle: 10


